namespace CoreTests;

/// <summary>
/// PLAN 2B.5c: 2B.5b'deki PrototypeTuning.Legacy.cs düz alan adlarının dondurulmuş listesi (247).
/// CI sığ klon olduğundan git geçmişine bakılmaz; bölüm tiplerinin bu kümeyi kapsadığı test edilir.
/// </summary>
internal static class PrototypeTuningLegacyFieldNames
{
    internal static readonly string[] All =
    {
        "ArenaHalfSizeM", "ArenaWallHeightM", "ArenaWallThicknessM", "ArenaVisualScale",
        "AmbientSky", "AmbientEquator", "AmbientGround", "FogColor",
        "FogDensity", "KeyLightColor", "KeyLightIntensity", "KeyLightEuler",
        "KeyShadowStrength", "RimLightColor", "RimLightIntensity", "RimLightEuler",
        "BloomIntensity", "BloomThreshold", "BloomScatter", "BloomTint",
        "PostExposure", "ColorContrast", "ColorSaturation", "ColorFilterTint",
        "PostVignetteIntensity", "CameraFarClipM", "TelegraphStretch", "TelegraphSquash",
        "TelegraphSlamSquash", "TelegraphTonePitchMin", "TelegraphTonePitchMax", "TelegraphToneVolumeMin",
        "TelegraphToneVolumeMax", "BossApproachStopPadM", "BossGravityMps2", "BossRecoilEaseDecayPerSec",
        "BossShakeAmpBaseM", "BossShakeAmpPerKnockbackM", "BossPinShakeAmpM", "BossLiftVelocityPerM",
        "ActiveBossId", "BossTurnRateDegPerSec", "BossSlamImpactNorm", "BossConeImpactNorm",
        "BossStaggerMinGapSec", "BossAnimCrossFadeSec", "BossWalkClipMps", "BossDeathCollapseSec",
        "BossDeathSquashY", "BossDeathSpreadXz", "FollowSmoothTimeSec", "LookAheadM",
        "CameraShoulderOffset", "CameraDistanceM", "CameraLookHeightM", "CameraFovDeg",
        "CameraAimDampingSec", "CameraSoftLockRangeM", "CameraSoftLockStrength", "CameraBossFramingWeight",
        "CameraBossAimHeightM", "CameraDefaultPitchDeg", "CameraLockOnMinDistanceM", "CameraLockOnMaxDistanceM",
        "CameraLockOnDistancePerSepM", "CameraLockOnMaxExtraDistanceM", "CameraLockOnDistanceSmoothSec", "CameraWindupDistanceMul",
        "CameraWindupExtraHeightM", "CameraWindupSmoothSec", "CameraWindupMinRadiusM", "CameraCollisionSphereRadiusM",
        "CameraCollisionMarginM", "CameraCollisionMinDistanceM", "CameraCollisionPullInSmoothSec", "CameraCollisionPullOutSmoothSec",
        "CameraLockOnShoulderSideM", "CameraLockOnShoulderFlipHysteresis", "CameraLockOnLookBlendToBoss", "OrbitDegreesPerDp",
        "CameraPitchMinDeg", "CameraPitchMaxDeg", "OrbitInvertPitch", "SoftAimRangeM",
        "SoftAimConeDeg", "WindowCueUrgentRatio", "WindowCuePulseHz", "WindowCueUrgentHz",
        "WindowCuePulseAmp", "AfterimageAlpha", "ImpactFadeSec", "VignetteHoldSec",
        "VignetteFadeSec", "VignetteAlpha", "ThreatAlphaMax", "ThreatPulseHzMin",
        "ThreatPulseHzMax", "CameraShakePxToM", "ReadoutAnchorRight", "ReadoutPunchInSec",
        "VitalsBarWidthDp", "VitalsBarHeightDp", "VitalsBossBarHeightDp", "VitalsBossBarWidthDp",
        "VitalsBarSpacingDp", "VitalsMarginDp", "VitalsHeaderHeightDp", "VitalsPanelPaddingDp",
        "BossVitalsColor", "StatusIconSizeDp", "StatusIconGapDp", "DamageFloatFontDp",
        "DamageFloatCritFontDp", "DamageFloatRisePx", "DamageFloatHoldSec", "DamageFloatFadeSec",
        "DamageFloatPunchScale", "RecoveryLockHeightDp", "RecoveryLockGapDp", "ShowFrameTimeHud",
        "FrameTimeSampleSec", "TargetFrameRateHz", "ShowDamageNumbers", "SkillPreviewWidthDp",
        "SkillPreviewHeightDp", "SkillPreviewGapDp", "SkillPreviewHoldSec", "SkipBuildSelectOnStart",
        "ShowSentenceDebugHud", "JoystickMaxRadiusDp", "JoystickDeadZone", "HudFitShortSideDp",
        "HexagonCenterXNorm", "HexagonCenterYNorm", "HexagonRadiusDp", "DotHitRadiusDp",
        "CenterHitRadiusDp", "MirrorForLeftHand", "InkLingerSec", "InkWidthDp",
        "InkRawWidthScale", "InkRawGlow", "DodgeButtonOffsetXDp", "DodgeButtonOffsetYDp",
        "DodgeButtonRadiusDp", "DodgeButtonScreenMarginDp", "DodgeClearanceDp", "WeaponSwapButtonRadiusDp",
        "WeaponSwapButtonOffsetXDp", "WeaponSwapButtonOffsetYDp", "WeaponSwapIconScale", "LockOnButtonRadiusDp",
        "LockOnButtonOffsetXDp", "LockOnButtonOffsetYDp", "LockOnButtonColor", "LockOnButtonActiveColor",
        "ElementMenuRadiusDp", "ElementMenuChipWidthDp", "ElementMenuChipHeightDp", "ElementMenuItemWidthDp",
        "ElementMenuItemHeightDp", "ElementMenuAnchorXNorm", "ElementMenuAnchorYNorm", "BasicStrikeDot",
        "IconDisplayScale", "CombatTrayPaddingDp", "CombatTrayHeaderHeightDp", "CombatTrayCornerRadiusDp",
        "CombatTrayLinkWidthDp", "DotVibrationMs", "PlayerVisualHeightM", "BossVisualHeightM",
        "CharacterAnimSpeed", "WalkSpeedMps", "MoveAccelMps2", "MoveDecelMps2",
        "TurnRateDegPerSec", "MinStickSpeedFrac", "AnimSpeedDampSec", "LocoMaxPlaybackMult",
        "AnimCrossFadeSec", "BasicStrikeComboResetSec", "UpperBodyCastMinSpeed", "FootstepStrideM",
        "BossFootstepStrideM", "PlayerMaxHp", "DodgeGlideSpeedMps", "PlayerColor",
        "BossColor", "GroundColor", "BackgroundColor", "InkPurple",
        "InkCyan", "AcidGreen", "ElementFire", "ElementWater",
        "ElementAir", "ElementEarth", "ElementLight", "ElementDark",
        "VfxTexFire", "VfxTexWater", "VfxTexAir", "VfxTexEarth",
        "VfxTexLight", "VfxTexDark", "VfxTexHit", "VfxTexInk",
        "HexagonDotColor", "HexagonCenterColor", "DodgeButtonColor", "TelegraphHot",
        "TelegraphWarm", "EffectLineWidthDefaultM", "EffectLineWidthWideM", "EffectLineWidthNarrowM",
        "EffectSarsintiWidthWideM", "EffectSarsintiWidthNarrowM", "EffectShowMinFocus", "EffectIgneShowMinSpread",
        "EffectFocusRingMax", "EffectFocusArcMax", "EffectPierceNeedleShowMin", "EffectFocusSwarmAlongLineMin",
        "EffectBlobScaleBaseM", "EffectBlobScalePerSpreadM", "EffectNeedleThickWideM", "EffectNeedleThickNarrowM",
        "EffectNeedleLenBaseM", "EffectNeedleLenPerPierceM", "EffectNeedleWindupLenMul", "EffectNeedleArrivalLenMul",
        "EffectNeedleAfterimageAlpha", "EffectSwarmJitterM", "EffectSwarmMinBlobs", "EffectSarsintiGroundY",
        "EffectSarsintiMassWidthMul", "EffectBasicStrikeLenM", "EffectBasicStrikeThickM", "EffectBasicStrikeHeightM",
        "ActorPoseDurationMs", "PoseIgne", "PoseSuru", "PoseSarsinti",
        "PoseKabuk", "PoseZehir", "GroundScarCapCount",
    };
}
