"""Deterministic generator for the Deneme Sahnesi open lava plain.
All coordinates in UNITY space (left-handed, Y up, metres). OBJ files are written with x negated
(Unity's OBJ importer negates x again), so Unity sees exactly these coordinates.
Outputs: Ground_Near.obj, Ground_Far.obj, LavaCracks.obj, Skyline.obj, EdgeMist.obj, DenemeSahnesiLayout.json
"""
import numpy as np, json, math, os
OUT='/workspace/karakterler/visual-testscene/out/Generated'
rng=np.random.default_rng(20261001)

# ---------- height field ----------
def vnoise_factory(seed):
    r=np.random.default_rng(seed); P=r.random((256,256))
    def n(x,y):
        xi=np.floor(x).astype(int); yi=np.floor(y).astype(int); xf=x-xi; yf=y-yi
        u=xf*xf*(3-2*xf); v=yf*yf*(3-2*yf)
        a=P[xi%256,yi%256]; b=P[(xi+1)%256,yi%256]; c=P[xi%256,(yi+1)%256]; d=P[(xi+1)%256,(yi+1)%256]
        return (a*(1-u)+b*u)*(1-v)+(c*(1-u)+d*u)*v
    return n
N1=vnoise_factory(1); N2=vnoise_factory(2)
def fbm(n,x,y,oct=4):
    s=0; a=0.5; f=1.0
    for _ in range(oct): s+=a*(n(x*f,y*f)-0.5); a*=0.5; f*=2.03
    return s
def height(x,z):
    x=np.asarray(x,float); z=np.asarray(z,float); r=np.hypot(x,z)
    near=fbm(N1,x/9+50,z/9+50)*0.9                     # +-0.4 m gentle basalt swell
    flat=np.clip((r-5)/10,0,1)                            # hero area flat
    mid=fbm(N2,x/40+10,z/40+10,5)*6*np.clip((r-35)/40,0,1)   # rolling beyond the boundary
    far=np.clip((r-150)/500,0,1)**1.3*14*(0.6+fbm(N1,x/180,z/180,3)+0.4)  # horizon rise
    return near*flat+mid+far

# ---------- polar ground mesh ----------
radii=list(np.arange(0,15.01,0.9))
while radii[-1]<1000: radii.append(radii[-1]*1.06)
radii=np.array(radii); SEG=160
split=int(np.argmin(np.abs(radii-75)))
def write_obj(path,V,UV,F,Nrm=None,header=''):
    with open(path,'w') as f:
        f.write(f'# {header}\n# generated by gen_layout.py (box). x is negated for Unity OBJ import.\n')
        for v in V: f.write(f'v {-v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n')
        for t in UV: f.write(f'vt {t[0]:.5f} {t[1]:.5f}\n')
        if Nrm is not None:
            for n in Nrm: f.write(f'vn {-n[0]:.4f} {n[1]:.4f} {n[2]:.4f}\n')
        for a,b,c in F:
            a+=1;b+=1;c+=1
            if Nrm is not None: f.write(f'f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n')
            else: f.write(f'f {a}/{a} {b}/{b} {c}/{c}\n')
def vnormals(V,F):
    n=np.zeros_like(V); fn=np.cross(V[F[:,1]]-V[F[:,0]],V[F[:,2]]-V[F[:,0]])
    for k in range(3): np.add.at(n,F[:,k],fn)
    return n/np.linalg.norm(n,axis=1,keepdims=True)
def polar_ring_mesh(r_list):
    th=np.linspace(0,2*np.pi,SEG,endpoint=False)
    V=[];UV=[]
    centre = r_list[0]==0
    rows=[]
    for r in r_list:
        if r==0:
            rows.append([len(V)]); V.append([0,height(0,0),0]); UV.append([0,0]); continue
        row=[]
        for t in th:
            x,z=r*math.cos(t),r*math.sin(t); row.append(len(V)); V.append([x,float(height(x,z)),z]); UV.append([x,z])
        rows.append(row)
    F=[]
    for i in range(len(rows)-1):
        A,B=rows[i],rows[i+1]
        for j in range(SEG):
            j2=(j+1)%SEG
            if len(A)==1: F.append([A[0],B[j2],B[j]]) # Unity-space winding: clockwise seen from +Y
            else:
                F.append([A[j],B[j2],B[j]]); F.append([A[j],A[j2],B[j2]])
    V=np.array(V,float); F=np.array(F)
    # Unity front faces are clockwise from the viewer; check normal points up with LH cross
    nrm=vnormals(V,F)
    if nrm[:,1].mean()>0:  # RH cross up => CCW from above in RH terms; flip to CW for Unity
        F=F[:,[0,2,1]]
    nrm=-vnormals(V,F) if vnormals(V,F)[:,1].mean()<0 else vnormals(V,F)
    return V,np.array(UV),F,nrm
V,UV,F,Nn=polar_ring_mesh(radii[:split+1])
write_obj(f'{OUT}/Ground_Near.obj',V,UV,F,Nn,f'Deneme Sahnesi near ground r<= {radii[split]:.1f} m, {len(F)} tris, UV0 = world XZ metres')
print('near',len(F),'tris r',radii[split])
V2,UV2,F2,N2n=polar_ring_mesh(radii[split:])
write_obj(f'{OUT}/Ground_Far.obj',V2,UV2,F2,N2n,f'Deneme Sahnesi far ground {radii[split]:.1f}..{radii[-1]:.0f} m, {len(F2)} tris')
print('far',len(F2),'tris to',radii[-1])

# ---------- lava cracks (ribbons) ----------
_TH=np.linspace(0,2*np.pi,SEG,endpoint=False)
_GRID=np.array([[float(height(r*math.cos(t),r*math.sin(t))) for t in _TH] for r in radii])
def mesh_h(x,z):
    r=math.hypot(x,z); t=math.atan2(z,x)%(2*np.pi)
    i=max(0,min(len(radii)-2,int(np.searchsorted(radii,r)-1))); fr=(r-radii[i])/(radii[i+1]-radii[i])
    j=int(t/(2*np.pi)*SEG)%SEG; j2=(j+1)%SEG; ft=t/(2*np.pi)*SEG-int(t/(2*np.pi)*SEG)
    if i==0 and radii[0]==0:
        a=_GRID[0,0]; b=_GRID[1,j]*(1-ft)+_GRID[1,j2]*ft; return a*(1-fr)+b*fr
    a=_GRID[i,j]*(1-ft)+_GRID[i,j2]*ft; b=_GRID[i+1,j]*(1-ft)+_GRID[i+1,j2]*ft
    return max(a*(1-fr)+b*fr, float(height(x,z)))

cracks=[]
def walk(start,ang,length,width,depth=0):
    pts=[np.array(start,float)]; a=ang; step=0.6
    n=int(length/step)
    for i in range(n):
        a+=rng.normal(0,0.22); p=pts[-1]+step*np.array([math.cos(a),math.sin(a)])
        if np.hypot(*p)<2.2: break
        pts.append(p)
        if depth<2 and i>3 and rng.random()<0.07:
            walk(p,a+rng.choice([-1,1])*rng.uniform(0.6,1.3),length*rng.uniform(0.25,0.5),width*0.55,depth+1)
    cracks.append((np.array(pts),width))
# main fissure toward the dragon (+Z), leading line from foreground
walk((1.8,-5.5),math.radians(84),70,0.42)
walk((-2.5,-3.0),math.radians(100),55,0.28)
for k in range(10):
    a0=rng.uniform(0,2*np.pi); r0=rng.uniform(4,26)
    walk((r0*math.cos(a0),r0*math.sin(a0)),rng.uniform(0,2*np.pi),rng.uniform(8,26),rng.uniform(0.10,0.22))
for k in range(8):  # far cracks
    a0=rng.uniform(0,2*np.pi); r0=rng.uniform(30,70)
    walk((r0*math.cos(a0),r0*math.sin(a0)),rng.uniform(0,2*np.pi),rng.uniform(10,30),rng.uniform(0.15,0.35))
CV=[];CUV=[];CF=[]
for pts,w in cracks:
    if len(pts)<3: continue
    seglen=np.r_[0,np.cumsum(np.linalg.norm(np.diff(pts,axis=0),axis=1))]; L=seglen[-1]
    base=len(CV)
    for i,p in enumerate(pts):
        d=pts[min(i+1,len(pts)-1)]-pts[max(i-1,0)]; d/=np.linalg.norm(d)+1e-9; nrm=np.array([-d[1],d[0]])
        taper=min(1,seglen[i]/2.5,(L-seglen[i])/2.5)**0.7
        ww=w*max(taper,0.08)*(0.75+0.5*N1(seglen[i]*0.7+base*0.01,3.3))*(1+np.hypot(*p)/9)
        for s,u in ((-1,0.0),(1,1.0)):
            q=p+nrm*ww*0.5*s; CV.append([q[0],mesh_h(q[0],q[1])+0.03+0.002*math.hypot(q[0],q[1]),q[1]]); CUV.append([u,seglen[i]])
    for i in range(len(pts)-1):
        a=base+2*i; CF.append([a,a+1,a+3]); CF.append([a,a+3,a+2])
# hot spots (glowing pools), like the mood photo
for k in range(40):
    pts,w=cracks[rng.integers(0,len(cracks))]; p=pts[rng.integers(0,len(pts))]+rng.normal(0,0.6,2)
    if np.hypot(*p)<2: continue
    rad=rng.uniform(0.18,0.55); seg=10; c=len(CV)
    CV.append([p[0],mesh_h(*p)+0.035,p[1]]); CUV.append([0.5,rng.uniform(0,50)])
    for j in range(seg):
        t=2*np.pi*j/seg; rr=rad*rng.uniform(0.6,1.25); q=p+rr*np.array([math.cos(t),math.sin(t)])
        CV.append([q[0],mesh_h(*q)+0.033,q[1]]); CUV.append([0.0,CUV[c][1]])
    for j in range(seg): CF.append([c,c+1+j,c+1+(j+1)%seg])
CV=np.array(CV); CF=np.array(CF)
# make all faces face up (Unity CW) using RH normal test
fn=np.cross(CV[CF[:,1]]-CV[CF[:,0]],CV[CF[:,2]]-CV[CF[:,0]])
flip=fn[:,1]>0; CF[flip]=CF[flip][:,[0,2,1]]
CN=np.tile([0,1,0],(len(CV),1))
write_obj(f'{OUT}/LavaCracks.obj',CV,np.array(CUV),CF,CN,f'lava crack ribbons + hot spots, {len(CF)} tris. UV.x = across (0 edge,0.5 core,1 edge), UV.y = metres along')
print('cracks',len(CF),'tris', len(cracks),'polylines')

# ---------- skyline (two ridge rings, unlit) ----------
SV=[];SUV=[];SF=[]
for (R,hmin,hmax,seed,segn) in ((470,18,70,3,180),(640,40,150,4,200)):
    nz=vnoise_factory(seed); base=len(SV)
    for j in range(segn+1):
        t=2*np.pi*j/segn; x,z=R*math.cos(t),R*math.sin(t)
        hh=hmin+(hmax-hmin)*np.clip(0.5+fbm(nz,j*0.09,seed*7.0,5)*1.6,0,1)
        # keep the far skyline lower straight behind the dragon so the head reads
        SV.append([x,-8,z]); SUV.append([0,0]); SV.append([x,hh,z]); SUV.append([1,0])
    for j in range(segn):
        a=base+2*j; SF.append([a,a+1,a+3]); SF.append([a,a+3,a+2])
SV=np.array(SV);SF=np.array(SF)
# faces must face the centre (viewer inside): RH normal should point inward
fn=np.cross(SV[SF[:,1]]-SV[SF[:,0]],SV[SF[:,2]]-SV[SF[:,0]]); cen=SV[SF].mean(1)
inward=(fn*(-cen)).sum(1)>0
SF[inward]=SF[inward][:,[0,2,1]]
write_obj(f'{OUT}/Skyline.obj',SV,np.array(SUV),SF,None,f'far skyline silhouette rings r470/r640, {len(SF)} tris, UV.x 0 bottom 1 top')
print('skyline',len(SF))

# ---------- edge mist band ----------
MV=[];MUV=[];MF=[]; R=44; segn=96
for j in range(segn+1):
    t=2*np.pi*j/segn; x,z=R*math.cos(t),R*math.sin(t); y0=float(height(x,z))-0.5
    MV.append([x,y0,z]); MUV.append([0,j/segn]); MV.append([x,y0+9,z]); MUV.append([1,j/segn])
for j in range(segn):
    a=2*j; MF.append([a,a+1,a+3]); MF.append([a,a+3,a+2])
MV=np.array(MV);MF=np.array(MF)
fn=np.cross(MV[MF[:,1]]-MV[MF[:,0]],MV[MF[:,2]]-MV[MF[:,0]]); cen=MV[MF].mean(1)
inward=(fn*(-cen)).sum(1)>0
MF[inward]=MF[inward][:,[0,2,1]]
write_obj(f'{OUT}/EdgeMist.obj',MV,np.array(MUV),MF,None,'edge mist band r44, UV.x 0 bottom 1 top')

# ---------- placements ----------
rocks=[]
FACING={'rock_face_01','rock_face_02','mountainside','namaqualand_cliff_02'}
def place(model,x,z,s,group,sink=0.25,tilt=6,jitter=35):
    if model in FACING:   # open-backed scans: turn the scanned face (+Z) toward the play area
        ry=math.degrees(math.atan2(-x,-z))+rng.uniform(-jitter,jitter)
    else: ry=rng.uniform(0,360)
    rocks.append(dict(model=model,group=group,pos=[round(x,3),round(float(height(x,z))-sink*s,3),round(z,3)],
                      rotY=round(float(ry%360),1),tilt=[round(float(rng.normal(0,tilt)),1),round(float(rng.normal(0,tilt)),1)],scale=round(s,3)))
# boundary: natural outcrop clusters r 30..42 with gaps; low boulders only in the dragon corridor
for k in range(10):
    ca=k*36+rng.uniform(-10,10)
    corridor=abs(((ca-90+180)%360)-180)<22
    if corridor:
        for j in range(3):
            a=ca+rng.uniform(-12,12); r=rng.uniform(33,40); x,z=r*math.cos(math.radians(a)),r*math.sin(math.radians(a))
            place('boulder_01',x,z,rng.uniform(1.6,2.6),'boundary',sink=0.35)
        continue
    for j in range(int(rng.integers(3,6))):
        a=ca+rng.uniform(-9,9); r=rng.uniform(31,41); x,z=r*math.cos(math.radians(a)),r*math.sin(math.radians(a))
        m=rng.choice(['rock_face_01','rock_face_02','boulder_01'],p=[0.22,0.23,0.55])
        s=rng.uniform(2.2,4.2) if m=='boulder_01' else rng.uniform(1.2,2.2)
        place(m,x,z,s,'boundary',sink=0.3 if m=='boulder_01' else 0.38,tilt=12)
# a few close foreground boulders for depth
for (x,z,s) in ((-6.5,6,1.3),(5.5,9,1.1),(-11,15,1.8),(9,-3,1.0)):
    place('boulder_01',x,z,s,'near',sink=0.3)
# mid scatter 50..150 m (kept clear of the dragon corridor so the head keeps its scale)
for k in range(26):
    a=rng.uniform(0,360); r=rng.uniform(52,150); x,z=r*math.cos(math.radians(a)),r*math.sin(math.radians(a))
    if abs(x)<34 and z>40: continue
    m=rng.choice(['rock_face_01','rock_face_02','boulder_01']); s=rng.uniform(2.5,4.5) if m=='boulder_01' else rng.uniform(1.8,3.5)
    place(m,x,z,s,'mid',sink=0.3,tilt=10)
# mountains 240..380 m, never straight behind the dragon (+-28 deg)
def ring_pos(rmin,rmax):
    while True:
        a=rng.uniform(0,360)
        if abs(((a-90+180)%360)-180)>28: break
    r=rng.uniform(rmin,rmax); return r*math.cos(math.radians(a)),r*math.sin(math.radians(a))
for k in range(9):
    x,z=ring_pos(250,380); place('mountainside',x,z,rng.uniform(5,8.5),'mountain',sink=0.15,tilt=3)
for k in range(7):
    x,z=ring_pos(180,300); place('namaqualand_cliff_02',x,z,rng.uniform(3.5,6),'mountain',sink=0.1,tilt=3)

dragon=dict(pos=[0.0,-7.0,96.0],rotY=180.0,scale=46.0,
            eyeL=[0.11,0.66,0.36],eyeR=[-0.11,0.66,0.36],eyeScale=[0.035,0.022,0.02])
hero=dict(pos=[-0.7,float(height(-0.7,0.0)),0.0],rotY=0.0)
camera=dict(start=[1.1,1.35,-8.0],end=[0.55,1.05,-3.9],lookAt=[-0.6,9.5,60.0],fov=50.0,duration=24.0)
lava_lights=[]
for pts,w in cracks[:2]+cracks[2:12]:
    for i in range(0,len(pts),9):
        x,z=pts[i]
        if np.hypot(x,z)<45: lava_lights.append(dict(pos=[round(x,2),round(float(height(x,z))+0.6,2),round(z,2)],range=round(3+8*w,2),intensity=round(1.2+3*w,2)))
lava_lights=lava_lights[:24]
probes=[]
for x in range(-15,16,6):
    for z in range(-12,19,6):
        for y in (0.6,3.0): probes.append([x,round(float(height(x,z))+y,2),z])
for (x,y,z) in ((0,5,70),(0,20,70),(-25,5,90),(25,5,90),(0,35,80),(-20,25,100),(20,25,100)): probes.append([x,y,z])
look=dict(fogColor=[0.690,0.718,0.737],fogDensity=0.0045,
          ambientSky=[0.66,0.70,0.73],ambientEquator=[0.52,0.55,0.58],ambientGround=[0.30,0.30,0.31],
          sunColor=[0.86,0.89,0.92],sunIntensity=0.85,sunEuler=[52.0,-30.0,0.0],shadowStrength=0.38,
          postExposure=0.15,contrast=-14.0,saturation=-22.0,colorFilter=[0.95,0.975,1.0],temperature=-8.0,
          bloomThreshold=0.95,bloomIntensity=0.65,bloomScatter=0.55,bloomTint=[1.0,0.86,0.72],vignette=0.12,
          lavaEdge=[0.06,0.045,0.04],lavaCore=[4.2,1.05,0.18],lavaPulse=0.25,
          skyBottom=[0.47,0.51,0.54],skyTop=[0.62,0.66,0.69],skyFogStrength=0.72,
          mistColor=[0.72,0.745,0.76],mistAlpha=0.38,
          dragonColor=[0.33,0.38,0.41],eyeColor=[5.0,2.2,0.5],rockTint=[0.86,0.89,0.92],groundTint=[0.95,0.97,1.0])
layout=dict(version=1,note='Unity space. Generated by gen_layout.py on the box; the builder reads this file.',
            groundTiling=7.0,detailTiling=1.8,rocks=rocks,dragon=dragon,hero=hero,camera=camera,
            lavaLights=lava_lights,boundary=dict(radius=33.0,segments=32,height=6.0,thickness=1.0),
            probesFlat=[round(float(c),2) for p in probes for c in p],look=look)
json.dump(layout,open(f'{OUT}/DenemeSahnesiLayout.json','w'),indent=1)
print('rocks',len(rocks),'lights',len(lava_lights),'probes',len(probes))
from collections import Counter; print(Counter(r['group'] for r in rocks))
